# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_page', '0004_auto_20170711_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballtype',
            name='comments',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
