# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_page', '0006_footballtype_is_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballtype',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
